# Generated by Django 2.0.9 on 2018-11-16 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20181106_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=12)),
                ('location', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('is_client', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientprofileinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='suplierprofileinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='ClientProfileInfo',
        ),
        migrations.DeleteModel(
            name='SuplierProfileInfo',
        ),
    ]
