# Generated by Django 2.0.9 on 2018-12-13 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
        ('accounts', '0003_auto_20181116_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='id_cluster',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='admin_app.Truck'),
        ),
    ]
