# Generated by Django 2.0.9 on 2018-12-16 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofileinfo_id_cluster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='location',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='id_cluster',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.Truck'),
        ),
    ]
