# Generated by Django 2.0.9 on 2018-11-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('genre', models.CharField(max_length=256)),
                ('id_client', models.CharField(max_length=256)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
