# Generated by Django 2.0.9 on 2018-11-26 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0003_checkout_orderedproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproducts',
            name='id_checkout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.Checkout'),
        ),
    ]
