# Generated by Django 2.0.9 on 2018-11-30 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0004_auto_20181126_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproducts',
            name='id_checkout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='order_app.Checkout'),
        ),
    ]
