# Generated by Django 2.0.9 on 2018-12-02 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id_checkout', models.IntegerField(primary_key=True, serialize=False)),
                ('name_client', models.CharField(max_length=256)),
                ('price', models.IntegerField()),
                ('weigth', models.IntegerField()),
                ('route_client', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('magazine', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('genre', models.CharField(max_length=256)),
                ('id_client', models.CharField(max_length=256)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderedProducts',
            fields=[
                ('id_order', models.IntegerField(primary_key=True, serialize=False)),
                ('name_deliver', models.CharField(max_length=256)),
                ('amount', models.IntegerField()),
                ('route', models.BooleanField(default=False)),
                ('id_route', models.IntegerField()),
                ('magazine', models.BooleanField(default=False)),
                ('id_checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='order_app.Checkout')),
                ('name_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_app.Product')),
            ],
        ),
    ]
