# Generated by Django 2.0.9 on 2018-12-09 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_auto_20181209_1346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
