# Generated by Django 2.0.9 on 2018-12-09 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0003_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproducts',
            name='id_checkout',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='order_app.Checkout'),
        ),
    ]
