# Generated by Django 2.0.9 on 2018-12-09 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0007_auto_20181209_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproducts',
            name='name_deliver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
